{
  "id": "CVE-2023-25399",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2023-07-05T17:15:09.320",
  "lastModified": "2023-07-05T17:15:09.320",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "A refcounting issue which leads to potential memory leak was discovered in scipy commit 8627df31ab in Py_FindObjects() function."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "http://www.square16.org/achievement/cve-2023-25399/",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/scipy/scipy/issues/16235",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/scipy/scipy/pull/16397",
      "source": "cve@mitre.org"
    }
  ]
}