{
  "id": "CVE-2023-3159",
  "sourceIdentifier": "secalert@redhat.com",
  "published": "2023-06-12T21:15:22.937",
  "lastModified": "2023-06-13T13:00:53.777",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "A use after free issue was discovered in driver/firewire in outbound_phy_packet_callback in the Linux Kernel. In this flaw a local attacker with special privilege may cause a use after free problem when queue_event() fails."
    }
  ],
  "metrics": {},
  "weaknesses": [
    {
      "source": "secalert@redhat.com",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-416"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://github.com/torvalds/linux/commit/b7c81f80246fac44077166f3e07103affe6db8ff",
      "source": "secalert@redhat.com"
    }
  ]
}