{
  "id": "CVE-2020-35588",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2022-12-07T08:15:09.107",
  "lastModified": "2022-12-07T08:15:09.107",
  "vulnStatus": "Rejected",
  "descriptions": [
    {
      "lang": "en",
      "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn. Further investigation showed that it was not a vulnerability. Notes: none."
    }
  ],
  "metrics": {},
  "references": []
}