{
  "id": "CVE-2023-3574",
  "sourceIdentifier": "security@huntr.dev",
  "published": "2023-07-10T16:15:56.527",
  "lastModified": "2023-07-10T16:27:17.833",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "Improper Authorization in GitHub repository pimcore/customer-data-framework prior to 3.4.1."
    }
  ],
  "metrics": {
    "cvssMetricV30": [
      {
        "source": "security@huntr.dev",
        "type": "Secondary",
        "cvssData": {
          "version": "3.0",
          "vectorString": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
          "attackVector": "NETWORK",
          "attackComplexity": "LOW",
          "privilegesRequired": "LOW",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "LOW",
          "integrityImpact": "LOW",
          "availabilityImpact": "LOW",
          "baseScore": 6.3,
          "baseSeverity": "MEDIUM"
        },
        "exploitabilityScore": 2.8,
        "impactScore": 3.4
      }
    ]
  },
  "weaknesses": [
    {
      "source": "security@huntr.dev",
      "type": "Primary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-285"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://github.com/pimcore/customer-data-framework/commit/f15668c86db254e86ba7ac895bc3cdd1a2a3cc45",
      "source": "security@huntr.dev"
    },
    {
      "url": "https://huntr.dev/bounties/1dcb4f01-e668-4aa3-a6a3-838532e500c6",
      "source": "security@huntr.dev"
    }
  ]
}