{
  "id": "CVE-2023-38469",
  "sourceIdentifier": "secalert@redhat.com",
  "published": "2023-11-02T15:15:08.167",
  "lastModified": "2023-11-07T04:17:18.883",
  "vulnStatus": "Undergoing Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "A vulnerability was found in Avahi, where a reachable assertion exists in avahi_dns_packet_append_record."
    },
    {
      "lang": "es",
      "value": "Se encontr\u00f3 una vulnerabilidad en Avahi, donde existe una afirmaci\u00f3n alcanzable en avahi_dns_packet_append_record."
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "attackVector": "LOCAL",
          "attackComplexity": "LOW",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "availabilityImpact": "HIGH",
          "baseScore": 6.2,
          "baseSeverity": "MEDIUM"
        },
        "exploitabilityScore": 2.5,
        "impactScore": 3.6
      }
    ]
  },
  "weaknesses": [
    {
      "source": "53f830b8-0a3f-465b-8143-3b8a9948e749",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-617"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://access.redhat.com/security/cve/CVE-2023-38469",
      "source": "secalert@redhat.com"
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2191687",
      "source": "secalert@redhat.com"
    }
  ]
}