{
  "id": "CVE-2020-26159",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2020-09-30T21:15:13.357",
  "lastModified": "2021-02-02T21:15:13.693",
  "vulnStatus": "Rejected",
  "descriptions": [
    {
      "lang": "en",
      "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Further investigation showed that it was not a security issue. Notes: none."
    }
  ],
  "metrics": {},
  "references": []
}