{
  "id": "CVE-2023-33595",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2023-06-07T20:15:09.920",
  "lastModified": "2023-06-07T20:24:12.193",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "CPython v3.12.0 alpha 7 was discovered to contain a heap use-after-free via the function ascii_decode at /Objects/unicodeobject.c."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "https://github.com/python/cpython/issues/103824",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/python/cpython/pull/103993/commits/c120bc2d354ca3d27d0c7a53bf65574ddaabaf3a",
      "source": "cve@mitre.org"
    }
  ]
}